### ISSUE TITLE
您好， offscreenPageLimit 属性设置之后不生效。

### ISSUE THREAD

**Issue by git-cncoder** [bxfx111/OrientedAutoViewPager#1]
代码是从Demo中复制过来的 不知道为什么只显示二个，不是四个。
![image](https://user-images.githubusercontent.com/22268505/44985762-094fd100-afb4-11e8-9146-2e52525376d8.png)

**Comment by FuXiangGit** [comment]
只需要控制布局宽度，和Transformer的一致，你这估计是布局右边太大遮挡了，你看demo里的fragment_card布局，文本有个右边距，这个边距你设置跟你要显示的最好适配，可以考虑动态计算

**Comment by git-cncoder** [comment]
@bxfx111  谢谢您解决了问题。原因是我将右边距写在了父布局中，导致无法显示正常的数量。
红色框是修改之后的。
![success.png](https://user-images.githubusercontent.com/22268505/45006300-bb29e480-b02a-11e8-9c25-20677ddbc840.png)
